### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by fnanni-0** [kleros/cross-chain-realitio-proxy#20]
@hbarcelos No vulnerabilities nor minor issues found.

https://docs.google.com/document/d/1Q33fR6WcpgzWcZhymZ7-QiV_xj4uRvhgI_7O1Akka0k/edit?usp=sharing

**Comment by hbarcelos** [comment]
Please see [@292adc](https://github.com/kleros/cross-chain-realitio-proxy/commit/292adc48457d290e9807e03a620c7d0be57bca9e)

**Comment by fnanni-0** [comment]
Looks good!
